name: cart-service ci/cd

on:
  push:
    tags:
      - cart-service-*

jobs:
  cart-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'deploy/build'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Extract Version
        id: extract_version_step
        run: |
          echo "tag=${GITHUB_REF#refs/*/}" >> "$GITHUB_OUTPUT"
      - name: Print Version
        run: |
          echo ${{ steps.extract_version_step.outputs.tag }}
#      - uses: actions/checkout@v2
#      - uses: docker/setup-qemu-action@v1
#        with:
#          platforms: linux/amd64,linux/arm64
#      - uses: docker/setup-buildx-action@v1
#      - uses: ./.github/actions
#        with:
#          version: ${{ env.PHP82 }}
#          tags: 8.2,8,latest
#          workdir: 8
#          platform: linux/amd64,linux/arm64
