name: cart-service

on:
  push:
    tags:
      - cart-service-*

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Extract Version
        id: extract_version_step
        run: |
          echo "tag=${GITHUB_REF#refs/*/}" >> "$GITHUB_OUTPUT"
      - name: Print Version
        run: |
          echo ${{ steps.extract_version_step.outputs.tag }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
#          platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare Docker Build Env
        run: |
          echo IMAGE_NAME=$(echo ${{ steps.extract_version_step.outputs.tag }} | rev | cut -d'-' -f2-  | rev) >> $GITHUB_ENV
          echo IMAGE_TAG=$(echo ${{ steps.extract_version_step.outputs.tag }} | rev | cut -d"-" -f1  | rev) >> $GITHUB_ENV
      - name: Prepare APP_RELATIVE_PATH
        run: |
          echo APP_RELATIVE_PATH=$(echo "$(echo ${{env.IMAGE_NAME}} | rev | cut -d'-' -f2-  | rev)/$(echo ${{env.IMAGE_NAME}} | rev | cut -d"-" -f1  | rev)") >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: 'deploy/build/Dockerfile'
#          platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.actor }}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
          build-args: APP_RELATIVE_PATH=${{env.APP_RELATIVE_PATH}}
