name: cart-service ci/cd

on:
  push:
    tags:
      - cart-service-*

jobs:
  cart-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'deploy/build'
    steps:
      - name: Extract Version
        id: version_step
        run: |
          echo "##[set-output name=version;]VERSION=${GITHUB_REF#$"refs/tags/v"}"
          echo "##[set-output name=version_tag;]$GITHUB_REPOSITORY:${GITHUB_REF#$"refs/tags/v"}"
          echo "##[set-output name=latest_tag;]$GITHUB_REPOSITORY:latest"
      - name: Print Version
        run: |
          echo ${{steps.version_step.outputs.version}}
          echo ${{steps.version_step.outputs.version_tag}}
          echo ${{steps.version_step.outputs.latest_tag}}
#      - uses: actions/checkout@v2
#      - uses: docker/setup-qemu-action@v1
#        with:
#          platforms: linux/amd64,linux/arm64
#      - uses: docker/setup-buildx-action@v1
#      - uses: ./.github/actions
#        with:
#          version: ${{ env.PHP82 }}
#          tags: 8.2,8,latest
#          workdir: 8
#          platform: linux/amd64,linux/arm64
