name: cart-service ci/cd

on:
  push:
    tags:
      - cart-service-*

jobs:
  cart-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'deploy/build'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Extract Version
        id: extract_version_step
        run: |
          echo "tag=${GITHUB_REF#refs/*/}" >> "$GITHUB_OUTPUT"
      - name: Print Version
        run: |
          echo ${{ steps.extract_version_step.outputs.tag }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare Image Name And Tag
        id: read-docker-image-identifiers
        run: |
          echo ${{ steps.extract_version_step.outputs.tag }} | rev | cut -d'-' -f2-  | rev
          echo ${{ steps.extract_version_step.outputs.tag }} | rev | cut -d"-" -f1  | rev
#          echo VERSION_TAG=$(echo ${{ steps.extract_version_step.outputs.version_tag }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
#      - uses: ./.github/actions
#        with:
#          version: ${{ env.PHP82 }}
#          tags: 8.2,8,latest
#          workdir: 8
#          platform: linux/amd64,linux/arm64
