name: cart-service

on:
  push:
    tags:
      - cart-service-*

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-image-action