name: order-service

on:
  push:
    tags:
      - order-service-*

env:
  SECRET_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: ./.github/actions
        with:
          secret_github_token: ${{ env.SECRET_GITHUB_TOKEN }}